# Travis-CI Build for OpenRA
# see travis-ci.org for details

language: csharp
mono: 6.4.0

jobs:
  include:
    - os: linux
      dist: xenial
    - os: osx
      if: tag IS present
      osx_image: xcode10

cache:
  directories:
  - thirdparty/download

addons:
  apt:
    packages:
    - lua5.1
    - dpkg
    - zsync
    - markdown

# Environment variables
env:

# Fetch dependencies
# Run the build script
# Check source code with StyleCop
# call OpenRA to check for YAML errors
# Run the NUnit tests
script:
 - make all
 - |
   if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      make check || travis_terminate 1;
      make check-scripts || travis_terminate 1;
      # make test || travis_terminate 1;
      mono ~/.nuget/packages/nunit.consolerunner/3.11.1/tools/nunit3-console.exe --noresult OpenRA.Test.dll || travis_terminate 1;
   fi

# Only watch the development branch and tagged release.
branches:
 only:
  - master

# Notify developers when build passed/failed.
notifications:
  webhooks: http://attsup.swr-productions.com/travis-ci/travis-ci.php

#before_deploy:
# - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
#     wget https://mirrors.edge.kernel.org/ubuntu/pool/universe/n/nsis/nsis-common_3.04-1_all.deb;
#     wget https://mirrors.edge.kernel.org/ubuntu/pool/universe/n/nsis/nsis_3.04-1_amd64.deb;
#     sudo dpkg -i nsis-common_3.04-1_all.deb;
#     sudo dpkg -i nsis_3.04-1_amd64.deb;
#     cd packaging && ./update-wiki.sh ${TRAVIS_TAG} && cd ..;
#   fi;
# - export PATH=$PATH:$HOME/usr/bin
# - DOTVERSION=`echo ${TRAVIS_TAG} | sed "s/-/\\./g"`
# - cd packaging
# - mkdir build
# - ./package-all.sh ${TRAVIS_TAG} ${PWD}/build/
# - cd itch && ./upload.sh ${TRAVIS_TAG} ${PWD}/build/
#deploy:
#  provider: releases
#  api_key:
#    secure: "g/LU11f+mjqv+lj0sR1UliHwogXL4ofJUwoG5Dbqlvdf5UTLWytw/OWSCv8RGyuh10miyWeaoqHh1cn2C1IFhUEqN1sSeKKKOWOTvJ2FR5mzi9uH3d/MOBzG5icQ7Qh0fZ1YPz5RaJJhYu6bmfvA/1gD49GoaX2kxQL4J5cEBgg="
#  file_glob: true
#  file: build/*
#  skip_cleanup: true
#  on:
#    all_branches: true
#    tags: true
#    repo: OpenRA/OpenRA
